# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RongCloudAppDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RongCloudIM/IMLib'
  pod 'RongCloudIM/IMKit'
  # Pods for RongCloudAppDemo

end
